In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [ ]:
state = tf.Variable(0, name = 'counter')
#print(state.name)

In [ ]:
one = tf.constant(5)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

In [ ]:
init = tf.global_variables_initializer()

In [ ]:
sess = tf.Session()
sess.run(init)

In [ ]:
for _ in range(3):
    sess.run(update)
    print(sess.run(state))

In [ ]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)

In [ ]:
output = tf.multiply(input1, input2)
sess = tf.Session()
res=sess.run(output,feed_dict = {input1: [7.], input2: [2.]})
print(res)

In [ ]:
print(sess.run(tf.random_normal([1,2])))

In [ ]:
def add_layer(inputs, in_size, out_size, activation_function = None):
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1,out_size])+0.1)
    Wx_plus_b = tf.matmul(inputs,Weights) + biases
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs
    
    
    

In [ ]:
x_data = np.linspace(-1,1,300)[:,np.newaxis]
#print(x_data.shape)
noise = np.random.normal(0, 0.05, x_data.shape)
y_data = np.square(x_data)  -0.5 + noise
#print(x_data)

In [ ]:
plt.scatter(x_data, y_data)
plt.show()

In [ ]:
xs = tf.placeholder(tf.float32,[None, 1])
ys = tf.placeholder(tf.float32, [None, 1])

In [ ]:
l1 = add_layer(xs, 1, 10, activation_function = tf.nn.relu)

In [ ]:
prediction = add_layer(l1, 10, 1, activation_function = None)

In [ ]:
loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys - prediction),axis = 1))

In [ ]:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

In [ ]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.scatter(x_data, y_data)
plt.ion()
plt.show()

In [ ]:
for i in range(1000):
    sess.run(train_step, feed_dict = {xs:x_data,ys:y_data})
    if (i % 50 ==0):
        try:
            ax.lines.remove(lines[0])
        except Exception:
            pass
        
        #print(sess.run(loss, feed_dict={xs:x_data,ys:y_data}))
        prediction_value = sess.run(prediction, feed_dict={xs:x_data})
        lines = ax.plot(x_data, prediction_value,'r-',lw = 5)
        plt.pause(1)
        plt.show(block=True)
    

In [ ]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]],[[4],[5],[6]]])

In [ ]:
x.shape
x

In [ ]:
x[...,0]

In [ ]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)


In [ ]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

In [ ]:
import numpy as np
a = np.zeros((2, 2))
#print(a)

In [ ]:
b = np.ones((1, 2))
print(b)

In [ ]:
import numpy as np
np.zeros([1,2])
print(np.full((2,2),3))
print(np.eye(2))
print(np.random.random((2,2)))

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
b = a[:2, 1:3]
b

In [ ]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
print(row_r1, row_r1.shape)
row_r2 = a[1:2, :]
print(row_r2)
print(row_r2.shape)

In [ ]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

In [ ]:
print(a[[0, 1, 2],[0, 1, 0]])

In [ ]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

In [ ]:
b = np.array([0, 2, 0, 1])
b

In [ ]:
print(a[np.arange(4), b])

In [ ]:
a[np.arange(4), b] += 10
print(a)

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

In [ ]:
bool_idx = (a > 2)
print(bool_idx)

In [ ]:
print(a[bool_idx])
print(a[(a > 2)])

In [ ]:
x = np.array([1, 2])
print(x.dtype)

In [ ]:
x = np.array([1.0, 2.0])
print(x.dtype)

In [ ]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
v = np.array([9,10])
w = np.array([11, 12])
#print(v)
print(v.dot(w))
print(np.dot(v, w))            

In [ ]:
print(x.dot(v))
print(np.dot(x, v))

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
x[0,:]

In [ ]:
y = np.empty_like(x)
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [ ]:
#We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [ ]:
v = np.array([1,2,3])[:,np.newaxis]  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
#print(np.reshape(v, (3, 1)) * w)
#print(w.shape)
print(v*w)

In [ ]:
np.random.normal([2,5])

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# number 1 to 10 data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

def add_layer(inputs, in_size, out_size, activation_function=None,):
    # add one more layer and return the output of this layer
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1,)
    Wx_plus_b = tf.matmul(inputs, Weights) + biases
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b,)
    return outputs

def compute_accuracy(v_xs, v_ys):
    global prediction
    y_pre = sess.run(prediction, feed_dict={xs: v_xs})
    correct_prediction = tf.equal(tf.argmax(y_pre,1), tf.argmax(v_ys,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    result = sess.run(accuracy, feed_dict={xs: v_xs, ys: v_ys})
    return result

# define placeholder for inputs to network
xs = tf.placeholder(tf.float32, [None, 784]) # 28x28
ys = tf.placeholder(tf.float32, [None, 10])

# add output layer
prediction = add_layer(xs, 784, 10,  activation_function=tf.nn.softmax)

# the error between prediction and real data
cross_entropy = tf.reduce_mean(-tf.reduce_sum(ys * tf.log(prediction),
                                              axis=[1]))       # loss
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

sess = tf.Session()
# important step
# tf.initialize_all_variables() no long valid from
# 2017-03-02 if using tensorflow >= 0.12

init = tf.global_variables_initializer()
sess.run(init)

for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={xs: batch_xs, ys: batch_ys})
    if i % 50 == 0:
        print(compute_accuracy(
            mnist.test.images, mnist.test.labels))

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# number 1 to 10 data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

In [ ]:
type(mnist)

In [ ]:
mnist.train.images.shape

In [ ]:
mnist.test.images.shape

In [ ]:
mnist.validation.images.shape

In [ ]:
#mnist.train.images[0].reshape(28, 28)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.imshow(mnist.train.images[1].reshape(28,28),cmap='Greys')

In [ ]:
import numpy as np

In [ ]:
a = np.array([1.0, 2.0, 3.0])[:,np.newaxis]

In [ ]:
a

In [ ]:
c = 2
a*c

In [ ]:
b = np.array([5.0, 2.0, 7.0])

In [ ]:
b

In [ ]:
x = np.array([[1.0], [2], [3]])

In [ ]:
x

In [ ]:
a = np.array([1.0, 2.0, 3.0])[:,np.newaxis]
a

In [ ]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)

In [ ]:
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out

In [ ]:
np.empty([3,4])

In [ ]:
np.random.normal(0,0.5,8)

In [9]:
import numpy as np
b = np.zeros(10)

In [10]:
b.shape

(10,)

In [11]:
b

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [12]:
import tensorflow as tf

In [39]:
a = np.array([[2,3,6],
             [1,2,6],
             
             ])

In [40]:
a.shape

(2, 3)

In [46]:
b = np.ones(2)[:,np.newaxis]
b.shape

(2, 1)

In [47]:
a+b

array([[ 3.,  4.,  7.],
       [ 2.,  3.,  7.]])